/**
 * Renders the observation log into something a human who did not write this
 * suite can read: `docs/reference/spec-defects.md`, and a delimited block on
 * the console for pasting into an issue.
 *
 * The report is written whether or not anything failed. A run in which
 * everything matched is a result — it is the only evidence the supported
 * NetBox range can ever be widened from "unknown".
 */

import type { Observation, Verdict } from "./observations.js";

export interface ReportMeta {
  generatedAt: string;
  /** Redacted unless NETBOX_CONTRACT_INCLUDE_HOST=1. */
  instance: string;
  netboxVersion: string;
  schemaInfoVersion: string;
  tokenCapability: string;
  suiteOutcome: string;
}

const MARKER: Record<Verdict, string> = {
  match: "OK",
  mismatch: "DEFECT",
  info: "INFO",
  unverified: "N/A",
};

const ORDER: Verdict[] = ["mismatch", "unverified", "info", "match"];

function counts(observations: readonly Observation[]): Record<Verdict, number> {
  const tally: Record<Verdict, number> = {
    match: 0,
    mismatch: 0,
    info: 0,
    unverified: 0,
  };
  for (const o of observations) tally[o.verdict] += 1;
  return tally;
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function sections(observations: readonly Observation[]): string[] {
  const seen: string[] = [];
  for (const o of observations) if (!seen.includes(o.section)) seen.push(o.section);
  return seen.sort((a, b) => a.localeCompare(b));
}

export function renderMarkdown(
  observations: readonly Observation[],
  meta: ReportMeta,
): string {
  const tally = counts(observations);
  const defects = observations.filter((o) => o.verdict === "mismatch");
  const unverified = observations.filter((o) => o.verdict === "unverified");

  const lines: string[] = [
    "# Spec defects — NetBox live contract run",
    "",
    "Generated by `npm run test:contract` (`tests/contract/`). **Do not hand-edit:**",
    "the next run overwrites this file. Commit it when the numbers change.",
    "",
    "Each row compares what this codebase _derives_ from the instance's own",
    "`/api/schema/` against what the instance _actually did_ when asked. A `DEFECT`",
    "row is a bug in the derivation, in the error mapping, or in an assumption",
    "written down in `docs/reference/netbox-schema-derivation.md` — not a bug in",
    "the NetBox instance.",
    "",
    "## Run",
    "",
    "|                     |                              |",
    "| ------------------- | ---------------------------- |",
    `| Generated           | ${escapeCell(meta.generatedAt)} |`,
    `| Instance            | ${escapeCell(meta.instance)} |`,
    `| NetBox, /api/status/ | ${escapeCell(meta.netboxVersion)} |`,
    `| NetBox, schema info.version | ${escapeCell(meta.schemaInfoVersion)} |`,
    `| Token capability    | ${escapeCell(meta.tokenCapability)} |`,
    `| Outcome             | ${escapeCell(meta.suiteOutcome)} |`,
    "",
    `**${tally.mismatch} defect(s)**, ${tally.match} match(es), ` +
      `${tally.info} recorded observation(s), ${tally.unverified} not verifiable here ` +
      `— ${observations.length} check(s) total.`,
    "",
  ];

  lines.push("## Defects", "");
  if (defects.length === 0) {
    lines.push(
      "None. Every derived expectation this suite knows how to check held on this",
      "instance. That is a statement about this instance and this NetBox version,",
      "not about NetBox in general.",
      "",
    );
  } else {
    defects.forEach((o, index) => {
      lines.push(
        `### D${index + 1}. ${o.check}`,
        "",
        `- **Section:** ${o.section}`,
        `- **Derived / assumed:** ${o.derived}`,
        `- **Actual:** ${o.actual}`,
        ...(o.note === undefined ? [] : [`- **Consequence:** ${o.note}`]),
        "",
      );
    });
  }

  if (unverified.length > 0) {
    lines.push(
      "## Not verifiable on this instance",
      "",
      "These checks could not run — usually because the instance holds no objects of",
      "that type, or the endpoint is not installed. They remain unverified assumptions.",
      "",
      "| Check | Why |",
      "| ----- | --- |",
      ...unverified.map((o) => `| ${escapeCell(o.check)} | ${escapeCell(o.actual)} |`),
      "",
    );
  }

  lines.push(
    "## Full log",
    "",
    "Everything the suite looked at, including the checks that passed.",
    "",
  );
  for (const section of sections(observations)) {
    const rows = observations
      .filter((o) => o.section === section)
      .sort((a, b) => ORDER.indexOf(a.verdict) - ORDER.indexOf(b.verdict));
    lines.push(
      `### ${section}`,
      "",
      "| | Check | Derived | Actual |",
      "| --- | ----- | ------- | ------ |",
      ...rows.map(
        (o) =>
          `| ${MARKER[o.verdict]} | ${escapeCell(o.check)} | ${escapeCell(o.derived)} | ${escapeCell(o.actual)} |`,
      ),
      "",
    );
  }

  lines.push(
    "---",
    "",
    "Re-run with:",
    "",
    "```sh",
    "NETBOX_URL=https://netbox.example.com \\",
    "NETBOX_TOKEN=<read-only token> \\",
    "npm run test:contract",
    "```",
    "",
  );

  return lines.join("\n");
}

export const BLOCK_BEGIN = "===== NETBOX CONTRACT REPORT BEGIN =====";
export const BLOCK_END = "===== NETBOX CONTRACT REPORT END =====";

/** A compact, pasteable summary for an operator who only has a terminal. */
export function renderConsoleBlock(
  observations: readonly Observation[],
  meta: ReportMeta,
): string {
  const tally = counts(observations);
  const lines: string[] = [
    BLOCK_BEGIN,
    `instance          : ${meta.instance}`,
    `netbox-version    : ${meta.netboxVersion}`,
    `schema info.version: ${meta.schemaInfoVersion}`,
    `token             : ${meta.tokenCapability}`,
    `outcome           : ${meta.suiteOutcome}`,
    `checks            : ${observations.length} total — ${tally.mismatch} DEFECT, ` +
      `${tally.match} OK, ${tally.info} INFO, ${tally.unverified} N/A`,
    "",
  ];

  for (const section of sections(observations)) {
    lines.push(`--- ${section} ---`);
    for (const o of observations
      .filter((x) => x.section === section)
      .sort((a, b) => ORDER.indexOf(a.verdict) - ORDER.indexOf(b.verdict))) {
      lines.push(`  [${MARKER[o.verdict].padEnd(6)}] ${o.check}`);
      lines.push(`             derived: ${o.derived}`);
      lines.push(`             actual : ${o.actual}`);
      if (o.note !== undefined) lines.push(`             note   : ${o.note}`);
    }
    lines.push("");
  }

  lines.push(BLOCK_END);
  return lines.join("\n");
}
